"""Add notifications table

Revision ID: 1cb0afe57d5b
Revises: 2dc00090c2c2
Create Date: 2026-10-02 08:29:48.192616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb0afe57d5b'
down_revision = '2dc00090c2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('warning', sa.String(length=200), nullable=False),
    sa.Column('footer', sa.String(length=200), nullable=False),
    sa.Column('style', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_style'), ['style'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_style'))
        batch_op.drop_index(batch_op.f('ix_notifications_starts_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_active'))
        batch_op.drop_index(batch_op.f('ix_notifications_ends_at'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
