"""add match finished timestamp

Revision ID: 2dc00090c2c2
Revises: 7219b15f1235
Create Date: 2026-09-28 12:26:47.066176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc00090c2c2'
down_revision = '7219b15f1235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_matches_finished_at'), ['finished_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_finished_at'))
        batch_op.drop_column('finished_at')

    # ### end Alembic commands ###
