"""Initial PinnaclePicks database

Revision ID: 7219b15f1235
Revises: 
Create Date: 2026-09-25 17:44:51.922452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7219b15f1235'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combo_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('total_odds', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('outcome_status', sa.String(length=20), nullable=False),
    sa.Column('required_tier', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('combo_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_combo_tickets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_combo_tickets_outcome_status'), ['outcome_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_combo_tickets_required_tier'), ['required_tier'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=150), nullable=False),
    sa.Column('away_team', sa.String(length=150), nullable=False),
    sa.Column('league', sa.String(length=150), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_type', sa.String(length=30), nullable=False),
    sa.Column('pick_selection', sa.String(length=100), nullable=False),
    sa.Column('odds', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('is_win', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_away_team'), ['away_team'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_home_team'), ['home_team'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_kickoff_time'), ['kickoff_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_league'), ['league'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_market_type'), ['market_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)

    op.create_table('media_proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_proofs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_proofs_uploaded_at'), ['uploaded_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_subscription_expires_at'), ['subscription_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_subscription_tier'), ['subscription_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('combo_matches',
    sa.Column('combo_ticket_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['combo_ticket_id'], ['combo_tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('combo_ticket_id', 'match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combo_matches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_subscription_tier'))
        batch_op.drop_index(batch_op.f('ix_users_subscription_expires_at'))
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('media_proofs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_proofs_uploaded_at'))

    op.drop_table('media_proofs')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_market_type'))
        batch_op.drop_index(batch_op.f('ix_matches_league'))
        batch_op.drop_index(batch_op.f('ix_matches_kickoff_time'))
        batch_op.drop_index(batch_op.f('ix_matches_home_team'))
        batch_op.drop_index(batch_op.f('ix_matches_away_team'))

    op.drop_table('matches')
    with op.batch_alter_table('combo_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combo_tickets_required_tier'))
        batch_op.drop_index(batch_op.f('ix_combo_tickets_outcome_status'))
        batch_op.drop_index(batch_op.f('ix_combo_tickets_created_at'))

    op.drop_table('combo_tickets')
    # ### end Alembic commands ###
